version: '3.8'

services:
  myapp:
    image: myapp:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8421:8421"
    volumes:
      - ./contracts:/opt/handstack/contracts
      - ./log:/opt/handstack/log
      - ./modules:/opt/handstack/modules
      - ./sqlite:/opt/handstack/sqlite
      - ./storage:/opt/handstack/storage
    entrypoint: ["dotnet", "ack.dll"]