services:
  database:
    image: mariadb:11.4
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${HOST_PORT}:3306"
    volumes:
      - dbp_${TENANT_ID}_mariadb_data:/var/lib/mysql
      - ./backups:/backups

volumes:
  dbp_${TENANT_ID}_mariadb_data:
