services:
  database:
    image: mysql:8.4
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${HOST_PORT}:3306"
    volumes:
      - dbp_${TENANT_ID}_mysql_data:/var/lib/mysql
      - ./backups:/backups

volumes:
  dbp_${TENANT_ID}_mysql_data:
