flowchart TB
    root[/Project Root/]
    WebHost[WebHost]
    Modules[Modules]
    Infra[Infrastructure]
    Tools[Tools]
    Contracts[Contracts]
    root --> WebHost
    root --> Modules
    root --> Infra
    root --> Tools
    root --> Contracts
